import Footer from "./component/footer";
import Header from "./component/header";
import "./globals.css";
import { Nunito } from "next/font/google";
import { nav } from "./data/data";

const inter = Nunito({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Rental app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <Header navLinks={nav} />

        {children}
        <Footer />
      </body>
    </html>
  );
}
